services:
  mssql:
    image: mcr.microsoft.com/mssql/server:${SERVER_VERSION}
    env_file: ./.env
    working_dir: /${WORKING_DIR}
    ports:
      - ${PORT}:${PORT}
    volumes: 
      - ./${MOUNT_NAME}:/${MOUNT_NAME}